package com.company.week1reviewexercise;

import java.util.Scanner;
import java.util.concurrent.ThreadLocalRandom;

public class Game {

    public static int startGame(){
        Scanner scanner = new Scanner(System.in);

        //start game
        System.out.println("Welcome to Rock, Paper, Scissors \n Choose: Rock(1), Paper(2), Scissors(3)");
        //create a variable to hold the user reponse using the Scanner object. The response needs to be an integer between 1-3 (1 = Rock, 2 = Paper, 3 = Scissors)
        int userResponse = scanner.nextInt();
        // create a variable to hold the cpu response generated by the getCPUResponse() method.
        int CPUResponse = getCPUResponse();

        System.out.println("The computer picked: " + CPUResponse);
        if (userResponse == 1) {
            Rock rock = new Rock(CPUResponse) ;
            int response = rock.checkOutcome();
            if (response == 1){
                System.out.println("Player wins: Rock beats Scissors");
            } else if (CPUResponse == 1) {
                System.out.println("Tie: Rock and Rock");
            } else {
                System.out.println("Player lose: Paper beats Rock");
            }
        } else if (userResponse == 2) {
            Paper paper = new Paper(CPUResponse) ;

            int response = paper.checkOutcome();
            if (response == 1){
                System.out.println("Player wins: Paper beats Rock");
            } else if (CPUResponse == 2) {
                System.out.println("Tie: Paper and Paper");
            } else {
                System.out.println("Player lose: Scissors beats Paper");
            }
        } else if (userResponse == 3 ) {
            Scissors scissors = new Scissors(CPUResponse) ;
            int response = scissors.checkOutcome();
            if (response == 1){
                System.out.println("Player wins: Scissors beats Paper");
            } else if (CPUResponse == 3) {
                System.out.println("Tie: Scissors and Scissors");
            } else {
                System.out.println("Player lose: Rock beats Scissors");
            }
        }


        System.out.println("Would like to play again? (1)Yes and (2)No");
        int playAgain = scanner.nextInt();
        if (playAgain == 1) {
            startGame();
        } else {
            System.exit(0);
        }


        return CPUResponse;
    }

    public static int getCPUResponse(){
        int randomNum = ThreadLocalRandom.current().nextInt(1, 3 + 1);
        // Generate random integers in range 1 to 3

        return randomNum;
    }
}
